Removed the code to import scenarios from connector
fortinet-fortisoar/soc-simulator pull request #25
Opened 2022-02-22 05:58 UTC by cs-swati-jinde

Removed the code to import scenarios from connector

2022-02-22 06:18 UTC, cs-tushar-kanade requested changes
Please do changes are per comments

2022-02-22 06:18 UTC, cs-tushar-kanade commented on fortisoar-soc-simulator/info.json
> -        "fields": [
Syntax error here , Fields [  ...

2022-02-22 06:18 UTC, cs-tushar-kanade commented on fortisoar-soc-simulator/info.json
> -        "fields": [
check RAW file , we see ] in file

2022-02-22 06:18 UTC, cs-tushar-kanade commented on fortisoar-soc-simulator/utils.py
> -        set_config_job(scenario_path,scenario_title=scenario)
apart from import_records there are supporting functions , please remove them as well .e.g set_config_job , get_config_job

2022-02-22 06:40 UTC, cs-swati-jinde commented on fortisoar-soc-simulator/info.json
> -        "fields": [
Resolved, Please review

2022-02-22 06:42 UTC, cs-swati-jinde commented on fortisoar-soc-simulator/utils.py
> -        set_config_job(scenario_path,scenario_title=scenario)
Resolved, removed get_config_job(),set_config_job,_upload_file,_create_import_job

2022-03-14 07:49 UTC, cs-swati-jinde commented
Following changes Done in Soc Simulator 2.0.0
1.Info.json - updated version, Removed the 'import scenario' checkbox option
2.Deleted the scenario folder with each scenario records

2022-03-14 07:58 UTC, cs-tushar-kanade approved these changes
Looks good

2022-03-14 07:58 UTC, cs-tushar-kanade commented
DO NOT MERGE YET , WE DO NOT WANT TO RELEASE CONNECTOR

2022-03-14 08:54 UTC, cs-suyog-jinturkar commented on fortisoar-soc-simulator/utils.py
>  def load_threat():
What is this function do?

2022-03-23 12:05 UTC, merged